"""Persistent on-disk cache for LLM responses.

WHY this module exists at all
-----------------------------
The project rule is that the same inference is never paid for twice. That rule is not
about the money alone, it is about reproducibility: the experiment compares four
prompting strategies across three models over hundreds of passages, and a rerun of the
evaluation (for a fixed bug, a new metric, a supervisor question) must replay exactly the
same model outputs rather than resample them. Sampling again would silently change the
measured accuracy between two runs of the same code, which would make every number in the
report unfalsifiable. A cache keyed on everything that can change the output turns the
LLM, a nondeterministic remote service, into a deterministic local function.

WHY the key is what it is
-------------------------
The key hashes (provider, model, template name, template VERSION, strategy, passage,
temperature, max_tokens). Template version is in the key because editing a prompt is the
single most likely thing to happen during the study: without the version in the key an
edited prompt would silently return stale responses generated by the previous wording,
and the strategy comparison would be meaningless. KEY_SCHEMA_VERSION lets a future change
to the key layout invalidate old entries deliberately instead of colliding with them.

WHY one JSON file per entry
---------------------------
A single index file would have to be rewritten on every call and would be corrupted by an
interrupted run of several thousand calls. One small file per key, written atomically via
a temporary file and os.replace, means a crash can lose at most the call in flight, and a
half-written file can never be read back as a valid entry. Files are sharded into 256
subdirectories by the first two hex characters of the key so that a full run (roughly
6,000 calls) does not put thousands of entries in one directory.

The cache directory is read from LLM_CACHE_DIR (see .env.example), defaulting to
./llm_cache, which .gitignore already excludes: cached raw model responses are large and
are research artefacts, not source.
"""

from __future__ import annotations

import hashlib
import json
import os
import tempfile
from dataclasses import asdict, dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from loguru import logger

# Bump only when the layout of the key payload changes. Bumping invalidates every stored
# entry on purpose, which is the honest behaviour: old keys no longer mean what they said.
KEY_SCHEMA_VERSION = "1"

DEFAULT_CACHE_DIR = "./llm_cache"
CACHE_DIR_ENV = "LLM_CACHE_DIR"


@dataclass(frozen=True)
class CacheEntry:
    """One cached model response plus the accounting needed to report on the run.

    Token counts, cost and latency are stored (not recomputed on read) so that the cost
    and speed tables in the report can be rebuilt from the cache alone, months later,
    without re-calling any API.
    """

    response_text: str
    prompt_tokens: int = 0
    completion_tokens: int = 0
    cost_usd: float = 0.0
    latency_ms: float = 0.0
    created_at: str = ""  # UTC, ISO 8601
    # Provenance of the call itself. Redundant with the key, but the key is a hash and a
    # hash cannot be audited by a human reading the cache directory.
    provider: str = ""
    model: str = ""
    template: str = ""
    template_version: str = ""
    strategy: str = ""

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> CacheEntry:
        """Build an entry from stored JSON, ignoring unknown keys.

        Tolerating unknown keys means a future field can be added without making every
        previously cached response unreadable.
        """
        fields = {f for f in cls.__dataclass_fields__}
        return cls(**{k: v for k, v in data.items() if k in fields})


def utc_now_iso() -> str:
    """Timestamps are UTC and explicit, because the run may span machines and timezones."""
    return datetime.now(UTC).isoformat(timespec="seconds")


def make_key(
    *,
    provider: str,
    model: str,
    template_name: str,
    template_version: str,
    strategy: str,
    passage: str,
    temperature: float,
    max_tokens: int,
) -> str:
    """Return a stable sha256 key over everything that can change the model's answer.

    Keyword-only arguments are deliberate: a positional call site that silently swapped
    model and strategy would produce a plausible looking but wrong key, and the failure
    would show up as inexplicable cache misses rather than as an error.
    """
    payload = {
        "key_schema": KEY_SCHEMA_VERSION,
        "provider": provider,
        "model": model,
        "template_name": template_name,
        "template_version": template_version,
        "strategy": strategy,
        "passage": passage,
        "temperature": round(float(temperature), 6),
        "max_tokens": int(max_tokens),
    }
    blob = json.dumps(payload, sort_keys=True, ensure_ascii=False, separators=(",", ":"))
    return hashlib.sha256(blob.encode("utf-8")).hexdigest()


class LLMCache:
    """File backed response cache with hit/miss accounting.

    The counters are per-instance and in-memory: they describe one run of the pipeline
    ("this run avoided 4.10 USD of spend"), which is what belongs in the report, whereas
    a persistent lifetime counter would keep growing across unrelated experiments.
    """

    def __init__(self, cache_dir: str | Path | None = None) -> None:
        if cache_dir is None:
            cache_dir = os.environ.get(CACHE_DIR_ENV) or DEFAULT_CACHE_DIR
        self.cache_dir = Path(cache_dir).expanduser()
        self._hits = 0
        self._misses = 0
        self._writes = 0
        self._spend_avoided_usd = 0.0

    # -- layout ---------------------------------------------------------------------
    def path_for(self, key: str) -> Path:
        """Shard on the first two hex characters, so no directory holds thousands of files."""
        return self.cache_dir / key[:2] / f"{key}.json"

    # -- api ------------------------------------------------------------------------
    def get(self, key: str) -> CacheEntry | None:
        """Return the cached entry, or None on a miss.

        A corrupt or unreadable file counts as a miss rather than an error: the worst case
        is paying for one inference again, whereas raising here would abort a long batch
        run over a single bad file.
        """
        path = self.path_for(key)
        if not path.is_file():
            self._misses += 1
            return None
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
            entry = CacheEntry.from_dict(data)
        except (OSError, ValueError, TypeError) as exc:
            logger.warning("Unreadable cache entry {}, treating as a miss: {}", path, exc)
            self._misses += 1
            return None
        self._hits += 1
        self._spend_avoided_usd += float(entry.cost_usd)
        return entry

    def set(self, key: str, entry: CacheEntry) -> None:
        """Store an entry atomically. Never raises: losing a cache write must not lose a run."""
        path = self.path_for(key)
        try:
            path.parent.mkdir(parents=True, exist_ok=True)
            # Write to a sibling temp file then rename, so a reader never sees a partial file.
            fd, tmp_name = tempfile.mkstemp(dir=str(path.parent), suffix=".tmp")
            try:
                with os.fdopen(fd, "w", encoding="utf-8") as handle:
                    json.dump(entry.to_dict(), handle, ensure_ascii=False, indent=2)
                os.replace(tmp_name, path)
            except BaseException:
                Path(tmp_name).unlink(missing_ok=True)
                raise
        except OSError as exc:
            logger.warning("Could not write cache entry {}: {}", path, exc)
            return
        self._writes += 1

    def stats(self) -> dict[str, Any]:
        """Hit/miss accounting for this run, plus the spend the cache avoided.

        spend_avoided_usd sums the cost recorded when each hit was originally paid for, so
        it answers "what would this rerun have cost without the cache", which is the number
        the reproducibility section of the report needs.
        """
        lookups = self._hits + self._misses
        return {
            "cache_dir": str(self.cache_dir),
            "hits": self._hits,
            "misses": self._misses,
            "lookups": lookups,
            "hit_rate": (self._hits / lookups) if lookups else 0.0,
            "writes": self._writes,
            "entries_on_disk": self.count_entries(),
            "spend_avoided_usd": round(self._spend_avoided_usd, 6),
        }

    def count_entries(self) -> int:
        if not self.cache_dir.is_dir():
            return 0
        return sum(1 for _ in self.cache_dir.rglob("*.json"))
